import { MasterIngredient } from "@/types/master-ingredient";

/**
 * =============================================================================
 * NORMALIZE INGREDIENT
 * =============================================================================
 * Ensures all ingredient fields have safe default values.
 * Handles null/undefined values from database.
 * =============================================================================
 */
export const normalizeIngredient = (data: MasterIngredient): MasterIngredient => {
  return {
    ...data,
    product: data.product ?? "",
    vendor: data.vendor ?? "",
    item_code: data.item_code ?? null,
    common_name: data.common_name ?? null,
    case_size: data.case_size ?? "",
    unit_of_measure: data.unit_of_measure ?? "",
    recipe_unit_type: data.recipe_unit_type ?? "",
    storage_area: data.storage_area ?? "",
    units_per_case: data.units_per_case ?? 0,
    current_price: data.current_price ?? 0,
    recipe_unit_per_purchase_unit: data.recipe_unit_per_purchase_unit ?? 0,
    yield_percent: data.yield_percent ?? 100,
    cost_per_recipe_unit: Math.round((data.cost_per_recipe_unit ?? 0) * 10000) / 10000,
    archived: data.archived ?? false,
    // Inventory Units
    inventory_unit_type: data.inventory_unit_type ?? "",
    inventory_unit_cost: data.inventory_unit_cost ?? 0,
    // Reporting & Tracking
    vitals_tier: data.vitals_tier ?? "standard",
    inventory_schedule: data.inventory_schedule ?? [],
    show_in_price_ticker: data.show_in_price_ticker ?? false,
    alert_price_change: data.alert_price_change ?? false,
    alert_low_stock: data.alert_low_stock ?? false,
    par_level: data.par_level ?? undefined,
    reorder_point: data.reorder_point ?? undefined,
    // Allergens - Contains
    allergen_peanut: data.allergen_peanut ?? false,
    allergen_crustacean: data.allergen_crustacean ?? false,
    allergen_treenut: data.allergen_treenut ?? false,
    allergen_shellfish: data.allergen_shellfish ?? false,
    allergen_sesame: data.allergen_sesame ?? false,
    allergen_soy: data.allergen_soy ?? false,
    allergen_fish: data.allergen_fish ?? false,
    allergen_wheat: data.allergen_wheat ?? false,
    allergen_milk: data.allergen_milk ?? false,
    allergen_sulphite: data.allergen_sulphite ?? false,
    allergen_egg: data.allergen_egg ?? false,
    allergen_gluten: data.allergen_gluten ?? false,
    allergen_mustard: data.allergen_mustard ?? false,
    allergen_celery: data.allergen_celery ?? false,
    allergen_garlic: data.allergen_garlic ?? false,
    allergen_onion: data.allergen_onion ?? false,
    allergen_nitrite: data.allergen_nitrite ?? false,
    allergen_mushroom: data.allergen_mushroom ?? false,
    allergen_hot_pepper: data.allergen_hot_pepper ?? false,
    allergen_citrus: data.allergen_citrus ?? false,
    allergen_pork: data.allergen_pork ?? false,
    // Allergens - May Contain
    allergen_peanut_may_contain: data.allergen_peanut_may_contain ?? false,
    allergen_crustacean_may_contain: data.allergen_crustacean_may_contain ?? false,
    allergen_treenut_may_contain: data.allergen_treenut_may_contain ?? false,
    allergen_shellfish_may_contain: data.allergen_shellfish_may_contain ?? false,
    allergen_sesame_may_contain: data.allergen_sesame_may_contain ?? false,
    allergen_soy_may_contain: data.allergen_soy_may_contain ?? false,
    allergen_fish_may_contain: data.allergen_fish_may_contain ?? false,
    allergen_wheat_may_contain: data.allergen_wheat_may_contain ?? false,
    allergen_milk_may_contain: data.allergen_milk_may_contain ?? false,
    allergen_sulphite_may_contain: data.allergen_sulphite_may_contain ?? false,
    allergen_egg_may_contain: data.allergen_egg_may_contain ?? false,
    allergen_gluten_may_contain: data.allergen_gluten_may_contain ?? false,
    allergen_mustard_may_contain: data.allergen_mustard_may_contain ?? false,
    allergen_celery_may_contain: data.allergen_celery_may_contain ?? false,
    allergen_garlic_may_contain: data.allergen_garlic_may_contain ?? false,
    allergen_onion_may_contain: data.allergen_onion_may_contain ?? false,
    allergen_nitrite_may_contain: data.allergen_nitrite_may_contain ?? false,
    allergen_mushroom_may_contain: data.allergen_mushroom_may_contain ?? false,
    allergen_hot_pepper_may_contain: data.allergen_hot_pepper_may_contain ?? false,
    allergen_citrus_may_contain: data.allergen_citrus_may_contain ?? false,
    allergen_pork_may_contain: data.allergen_pork_may_contain ?? false,
    // Custom Allergens
    allergen_custom1_active: data.allergen_custom1_active ?? false,
    allergen_custom1_may_contain: data.allergen_custom1_may_contain ?? false,
    allergen_custom2_active: data.allergen_custom2_active ?? false,
    allergen_custom2_may_contain: data.allergen_custom2_may_contain ?? false,
    allergen_custom3_active: data.allergen_custom3_active ?? false,
    allergen_custom3_may_contain: data.allergen_custom3_may_contain ?? false,
  };
};

/**
 * =============================================================================
 * CREATE EMPTY INGREDIENT
 * =============================================================================
 * Factory function for creating a new ingredient with all defaults set.
 * =============================================================================
 */
export const createEmptyIngredient = (organizationId: string): MasterIngredient => ({
  id: crypto.randomUUID(),
  organization_id: organizationId,
  product: "",
  major_group: null,
  category: null,
  sub_category: null,
  vendor: "",
  item_code: null,
  common_name: null,
  case_size: "",
  units_per_case: 0,
  recipe_unit_type: "",
  yield_percent: 100,
  cost_per_recipe_unit: 0,
  current_price: 0,
  recipe_unit_per_purchase_unit: 0,
  unit_of_measure: "",
  storage_area: "",
  image_url: null,
  archived: false,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  // Inventory Units
  inventory_unit_type: "",
  inventory_unit_cost: 0,
  // Reporting & Tracking
  vitals_tier: "standard",
  inventory_schedule: [],
  show_in_price_ticker: false,
  alert_price_change: false,
  alert_low_stock: false,
  par_level: undefined,
  reorder_point: undefined,
  // Ingredient type
  ingredient_type: "purchased",
  source_recipe_id: null,
  // Allergens - Contains (all false)
  allergen_peanut: false,
  allergen_crustacean: false,
  allergen_treenut: false,
  allergen_shellfish: false,
  allergen_sesame: false,
  allergen_soy: false,
  allergen_fish: false,
  allergen_wheat: false,
  allergen_milk: false,
  allergen_sulphite: false,
  allergen_egg: false,
  allergen_gluten: false,
  allergen_mustard: false,
  allergen_celery: false,
  allergen_garlic: false,
  allergen_onion: false,
  allergen_nitrite: false,
  allergen_mushroom: false,
  allergen_hot_pepper: false,
  allergen_citrus: false,
  allergen_pork: false,
  // Allergens - May Contain (all false)
  allergen_peanut_may_contain: false,
  allergen_crustacean_may_contain: false,
  allergen_treenut_may_contain: false,
  allergen_shellfish_may_contain: false,
  allergen_sesame_may_contain: false,
  allergen_soy_may_contain: false,
  allergen_fish_may_contain: false,
  allergen_wheat_may_contain: false,
  allergen_milk_may_contain: false,
  allergen_sulphite_may_contain: false,
  allergen_egg_may_contain: false,
  allergen_gluten_may_contain: false,
  allergen_mustard_may_contain: false,
  allergen_celery_may_contain: false,
  allergen_garlic_may_contain: false,
  allergen_onion_may_contain: false,
  allergen_nitrite_may_contain: false,
  allergen_mushroom_may_contain: false,
  allergen_hot_pepper_may_contain: false,
  allergen_citrus_may_contain: false,
  allergen_pork_may_contain: false,
  // Custom Allergens
  allergen_custom1_name: null,
  allergen_custom1_active: false,
  allergen_custom1_may_contain: false,
  allergen_custom2_name: null,
  allergen_custom2_active: false,
  allergen_custom2_may_contain: false,
  allergen_custom3_name: null,
  allergen_custom3_active: false,
  allergen_custom3_may_contain: false,
  allergen_notes: null,
});

export default { normalizeIngredient, createEmptyIngredient };
